remote_theme: mikearnaldi/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
'@evolution-sdk/experimental on GitHub':
  - 'https://github.com/no-witness-labs/evolution-sdk'
